<a href="https://colab.research.google.com/github/aruntahilramani/134_ArunTahilramani/blob/master/Lab9/134_SVM_MNIST_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment**:

Try SVM classifier on MNIST dataset, compare the performance of linear, polynomial and RBF kernels.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
# Load MNIST Dataset
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
# print the features
print(X_train[:2])
# print the labels
print(y_train[:2])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0]


In [4]:
# Size of training and testing
print('X_train : ', X_train.data.shape)
print('y_train : ', y_train.data.shape)
print('X_test : ', X_test.data.shape)
print('y_test : ', y_test.data.shape)

X_train :  (60000, 28, 28)
y_train :  (60000,)
X_test :  (10000, 28, 28)
y_test :  (10000,)


In [5]:
# Working with sample_size as the dataset is large
# Considering 10000 images and giving 8000 images to training and 2000 images to testing
train_sample_size = 8000
test_sample_size = 2000

X_train = X_train[:train_sample_size]
y_train = y_train[:train_sample_size]
X_test = X_test[:test_sample_size]
y_test = y_test[:test_sample_size]

In [6]:
print('X_train : ', X_train.data.shape)
print('y_train : ', y_train.data.shape)
print('X_test : ', X_test.data.shape)
print('y_test : ', y_test.data.shape)

X_train :  (8000, 28, 28)
y_train :  (8000,)
X_test :  (2000, 28, 28)
y_test :  (2000,)


In [7]:
# fit needs 2D array for training 
# So reshaping the numpy array from (sample_size, 28, 28) to (sample_size, 784)

samples, x, y = X_train.shape
X_train = X_train.reshape((samples, x*y))

samples, x, y = X_test.shape
X_test = X_test.reshape((samples, x*y))

**Linear Kernel**

In [8]:
# Create a model with linear kernel
# C - regularization (0-1)
# gamma
linearModel = SVC(kernel='linear')

In [9]:
# fit needs 2D array for training 
linearModel.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [10]:
# Model analysis
print('Linear kernel score : ', linearModel.score(X_test, y_test))

Linear kernel score :  0.887


**Polynomial Kernel**

In [11]:
# Create a model with polynomial kernel
polynomialModel = SVC(kernel='poly')

In [12]:
# fit needs 2D array for training 
polynomialModel.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
# Model analysis
print('Polynomial kernel score : ', polynomialModel.score(X_test, y_test))

Polynomial kernel score :  0.9255


**RBF Kernel**

In [14]:
# Create a model with rbf kernel
rbfModel = SVC(kernel='rbf')

In [15]:
# fit needs 2D array for training 
rbfModel.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
# Model analysis
print('Rbf kernel score : ', rbfModel.score(X_test, y_test))

Rbf kernel score :  0.942
