<a href="https://colab.research.google.com/github/aruntahilramani/134_ArunTahilramani/blob/master/Lab1/134_Lab1_LinearAlgebraWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2x3 = np.array([[1, 2, 4], [4, 5, 6]])

print('3 x 2 matrix : \n', matrix3x2)
print('\n 2 x 3 matrix : \n', matrix2x3)

3 x 2 matrix : 
 [[1 2]
 [3 4]
 [5 6]]

 2 x 3 matrix : 
 [[1 2 4]
 [4 5 6]]


In [3]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.94779915 0.74204872 0.07243155 0.19854284]
 [0.79667389 0.875189   0.89785513 0.22406242]
 [0.50549602 0.56523983 0.3339079  0.806239  ]]


In [4]:
# matrix multiplication
matmul = np.dot(matrix3x2, matrix2x3)
print(matmul)

[[ 9 12 16]
 [19 26 36]
 [29 40 56]]


In [5]:
# elemet wise matrix multiplication
result = [[0 for x in range(len(matrix3x2))] for y in range(len(matrix2x3[0]))]

for i in range(len(matrix3x2)): 
  for j in range(len(matrix2x3[0])): 
    for k in range(len(matrix2x3)): 
      result[i][j] += matrix3x2[i][k] * matrix2x3[k][j]
 
print('Element wise multiplication : \n', result)

Element wise multiplication : 
 [[9, 12, 16], [19, 26, 36], [29, 40, 56]]


In [6]:
mean = np.mean(matrix3x2)
print(mean)

3.5


In [7]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/Lab1/mtcars.csv')

In [8]:
del data['model']

meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
