<a href="https://colab.research.google.com/github/aruntahilramani/134_ArunTahilramani/blob/master/Lab6/134_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [3]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/Lab 6/BuyComputer.csv')

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:

#Declare label as last column in the source file
Y = data.iloc[:,-1]

In [5]:
#Declaring X as all columns excluding last
X = data.iloc[:,:2]

In [6]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=134,test_size=0.5)

In [7]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)
entries = len(X_train[:,0])
entries

2


200

In [9]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [10]:
# Sigmoid function
def sigmoid(z):
  sig = 1/(1+np.exp(-z))
  return sig

In [11]:
def predict(inputs):
    return np.matmul(inputs,w)+b
def h(inputs):
    return sigmoid(predict(inputs))

In [12]:
#Loss function
def loss_func(y,a):
    J = 0
    for i in range(0,len(y)):
        J += y[i]*np.log(h(X_train[i]))+(1-y[i])*np.log(1-h(X_train[i]))
    return -J
def gradient_descend(lr):
    tmp = h(X_train)
    for i in range(0,len_x):
        w[i]-=lr*np.sum((tmp.flatten()-y_train)*X_train[:,i])
    global b
    b-=lr*np.sum(tmp.flatten()-y_train)       

In [13]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

In [14]:
#Repeating the process 3000 times
for i in range(0,3000):
    gradient_descend(lr=alpha)

In [15]:
#Print weight
w

[4.437360659264182, 0.5772025602874662]

In [16]:
#print bias
b

-0.6601122512883757

In [17]:
#predicting the label
y_ = h(X_test)
y_ = y_.flatten()
y_predicted = (y_ >= .5).astype(int)
y_predicted

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0])

In [18]:
#print actual and predicted values in a table
y_test

368    0
229    1
208    1
153    0
296    1
      ..
349    0
235    1
334    1
111    0
177    0
Name: Purchased, Length: 200, dtype: int64

In [19]:
# Calculating accuracy of prediction
np.sum(y_predicted == y_test)/len(X_test)

0.81

In [20]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predicted)

array([[102,  20],
       [ 18,  60]])

In [21]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_predicted = LR.predict(X_test)

In [22]:
confusion_matrix(y_test, y_predicted)

array([[115,   7],
       [ 24,  54]])